### ISSUE TITLE
Erreur création d'un compte de tests

### ISSUE THREAD

**Issue by Arslack** [Horsty80/MagicTools-Feedback#2]
Se connecter à https://dev.magic-tools.fr/
Allez dans "Se connecter"
Puis dans "S'inscrire" 
Lors de la création, pas de message d'erreur ni de mail sur l'adresse temporaire.
Impossible se connecter avec le compte créer

**Comment by Horsty80** [comment]
> … pas de message d'erreur ni de mail sur l'adresse temporaire. Impossible se connecter avec le compte créer

peux tu m’indiquer:
- ce que tu entends par adresse temporaire ? 
- quel adresse as tu utilisé ? 

Tu as déjà un compte, si tu as essayer dans faire un autre avec un « + » je crois que le service d’auth que j’utilise n’est pas configuré pour le gérer 
Je vais regarder ce point

merci ✌️

**Comment by Arslack** [comment]
l'adresse mail est : nimomiw393@nozamas.com
le nom de compte test

**Comment by Horsty80** [comment]
Ah ! Je sais, j’ai pas encore ajouté le feedback sur la validité de ton mot de passe
Donc si ton mots de passe ne respecte pas des règles de sécurité ça ne sera pas créé

je vais rajouter un indicateur de validité de mot de passe ✌️

**Comment by Arslack** [comment]
Fonctionne correctement :)
