### ISSUE TITLE
Coté joueurs : Mes inscriptions (les inscriptions ne sont pas visibles) 

### ISSUE THREAD

**Issue by Arslack** [Horsty80/MagicTools-Feedback#3]
Un joueur peut s'inscrire à un évènement, du point de vu de l'organisateur l'inscription est bien visible mais dans Mes inscriptions, le joueurs ne vois pas les évènements auxquelles, il est inscrit.
![image](https://github.com/user-attachments/assets/22fe55c7-da40-4b40-b8fc-1095f5046f02)

**Comment by Horsty80** [comment]
Je dois vérifier un truc sur le cache qui n'est pas invalidé après l'inscription à un event.

Merci ✌️

**Comment by Horsty80** [comment]
Fix ! Je déploie dans la soirée.

J'avais modifié une requête et ajouter une condition qui excluait les résultats.
