### ISSUE TITLE
Coté Organisateur : réception des Deck List

### ISSUE THREAD

**Issue by Arslack** [Horsty80/MagicTools-Feedback#4]
L'envoi et la modification de la decklist fonctionne très bien coté Joueur. Cependant, il semblerais qu'on ne peut réceptionner qu'une seul decklist par évènement par exemple : 
![image](https://github.com/user-attachments/assets/a99424c7-d567-4c1a-97cd-83bea6918609)
J'ai envoyer la decklist avec Test1 puis avec mon compte clement. Sauf qu'il met a jour le lien uniquement pour le dernier utilisateur qui à envoyé la decklist et la supprime pour l'autre

**Comment by Horsty80** [comment]
Fix !

J'avais fait une erreur d'implémentation et de droit d'accès écriture/lecture au decklist, qui faisait qu'on éditer la même decklist x)
